# Generated by Django 5.2.14 on 2026-05-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Live', max_length=50),
        ),
    ]
